mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=lexicon
    - MYSQL_DATABASE=world
    - MYSQL_RANDOM_ROOT_PASSWORD=true
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"